lesson0-enに目的を追加 lesson2-serialを作成
NOKOLat/Programming_Documents pull request #7
Opened 2024-04-02 09:37 UTC by numa-sea

lesson2-serialを作成

2024-04-04 11:33 UTC, SatoshiRC commented on docs/ESP32/lesson2-serial.md
> +## 1. シリアル通信とは
シリアル通信は[このページ](https://nokolat.github.io/Programming_Documents/communication/#uart)のほうに詳しく書いてるから，リンクを貼るか，こちらをご覧くださいだけでもいいと思う

2024-04-04 11:59 UTC, SatoshiRC commented on docs/ESP32/lesson2-serial.md
> +- int data → char data, Serial.print(data, DEC); → Serial.print(data);に書き換えよう
出力結果が文字で表示されることが正しいと書いてあるが，それなら最初から文字で表示されるプログラムを示すべきだと思う．最初に数字で表示されるプログラムを使っているのはASCIIコードの説明をしたいからだと思うので，もう少し違った書き方がありそう．

現状の説明だと「ドキュメントに書いてあるプログラムをそのまま実行したのに正しくないの？？？」になりそう．

こんな感じに変えてみるのはどう？
---
### ASCIIコード
- ASCIIコードはアルファベットや記号を0から127までの数字で表す
- 例えば"a"は97, "\n"(改行)は10と表される
- Serial.print(data, DEC);は入力されたデータを10進数の数字としてASCIIコードに変換するし送信する
    - data = "a";のとき"a"はASCIIコードで10であるから，送信されるデータは"10"(文字列) となる
- Serial.print(data)は入力されたデータをそのまま送信する

`Serial.print(data, DEC);` を `Serial.print(data);` に書き換えて実行してみよう

2024-04-04 12:01 UTC, SatoshiRC commented on docs/ESP32/lesson2-serial.md
> +**次回はセンサーを使います！**
次回分のページが完成したらリンクを貼ろう

2024-04-04 12:03 UTC, SatoshiRC commented on docs/ESP32/lesson3-sensor.md
> +- センサーをArduino環境下のesp32で簡単に使えるようにするためのライブラリが多く存在する
ライブラリを使う作業にかんしてはesp32に限定されないので
`- センサーをArduino環境で簡単に使うライブラリが多く存在する`
としても良いと思う

2024-04-04 12:14 UTC, SatoshiRC commented on docs/ESP32/lesson3-sensor.md
> +- ライブラリの詳しい説明は後で書くが、イメージとしてはライブラリを使用すると自分で書くプログラムが楽になる便利なもの
- ライブラリはプログラムをかんたんに書くためのツールである
- ライブラリについて，詳しくは後述する
こんな感じにしたい

2024-04-04 12:19 UTC, SatoshiRC commented on docs/ESP32/lesson3-sensor.md
> +- 長いプログラムになってくると書き込みや実行速度が遅くなるためプログラムの処理を簡潔にすることは重要である
「長い」よりも「処理の多い」のほうが適切

「長いプログラム〜」だとソースコードの文字数を減らせば実行が早くなると誤解されない...？

2024-04-06 15:17 UTC, numa-sea commented
修正したものをプッシュしました
プッシュしたらコメントしたほうがいいですか？

2024-04-07 07:35 UTC, SatoshiRC approved these changes
指摘したところ直してくれてありがとう．
だいぶ良くなったと思います．

2024-04-10 07:06 UTC, numa-sea commented
lesson0-enを修正
lesson4-servoまでpushしてるかもしれない
index.mdとmkdocs.ymlにはlesson3-sensorまでしか追加してないのでlesson3までのチェックをお願いします

2024-04-10 07:13 UTC, SatoshiRC requested changes
細かい修正が必要そう

2024-04-15 01:10 UTC, SatoshiRC requested changes
この前のやつ，コメントがうまくつけられてなかったね．ゴメン

細かい修正はレビュアーがやっても良さそう

2024-04-15 01:10 UTC, SatoshiRC commented on docs/ESP32/lesson0-environment.md
> +これでArduino IDEでESP32, raspberry pi picoを使用するための環境が整いました！
raspi picoはもういないよね

2024-05-20 08:26 UTC, SatoshiRC approved these changes

2024-05-20 08:28 UTC, merged