ドキュメントの書き方を書いた
NOKOLat/Programming_Documents pull request #8
Opened 2024-04-05 06:22 UTC by SatoshiRC

2024-04-06 14:44 UTC, SatoshiRC reviewed
mkdocs を使ったプレビュー方法もこのページに書くべき

2024-04-06 14:59 UTC, numa-sea commented
ありがとうございます
変更したコードは見れるのですが、ほかの人が新規にコミットしたところのページはどうやったら確認することができますか？

2024-04-07 01:21 UTC, SatoshiRC commented
> ほかの人が新規にコミットしたところのページはどうやったら確認することができますか？

ローカルで確認したいブランチをチェックアウトすれば確認できます

2024-04-29 11:47 UTC, Genki-Kurose requested changes

2024-04-29 11:47 UTC, Genki-Kurose commented on docs/HowToWrite.md
> +    `pip install mkdocs`
これいらんくね？(体験談)

2024-04-29 11:52 UTC, Genki-Kurose approved these changes
ok

2024-05-10 04:33 UTC, merged